name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    # Allow to run manually from actions tab:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Build docker container
        run: echo Hello, world!
  
